### ISSUE TITLE
Add integration with Travis CI

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-igorkruglyak#14]
Please configure integration with TravisCI:
* [ ] [Enable repo testing in TravisCI](https://travis-ci.com/kpi-web-guild/django-girls-blog-igorkruglyak)
* [ ] Add TravisCI badge (master branch) to `README.md` with a single commit. (click ![Build Status](https://travis-ci.com/kpi-web-guild/django-girls-blog-igorkruglyak.svg?branch=master) next to octocat icon on [this page](https://travis-ci.com/kpi-web-guild/django-girls-blog-igorkruglyak))
* [ ] Create new branch called `feature/travis-ci-integration` and do all the following steps within that branch.
* [ ] Add `.travis.yml` using `pre-commit` as a script. Set it up to run Python 3.7 env and add PIP caching. Ensure you install `pre-commit` before running tests:
```yaml
language: python
python: 3.7
cache: pip
before_install: pip install -U pre-commit
script: pre-commit run --all-files
```
* [ ] Push the branch and create a Pull Request for it.
